### ISSUE TITLE
Accept Datetime as possible vary on arg

### ISSUE THREAD

**Issue by benrudolph** [dimagi/quickcache#9]
@dannyroberts Often I'm finding myself needing to break the cache based on my model's `updated_at` property that returns a datetime. Currently quickcache doesn't support that and errors. How would you feel about a PR to add handling of a datetime type to this function: https://github.com/dimagi/quickcache/blob/master/quickcache/quickcache_helper.py#L96 that simple calls `isoformat` on the object if it is a datetime?

**Comment by dannyroberts** [comment]
Yeah sure, I'd be open to reviewing that contribution! There's a legit question though that you'll be answering when you make the change, whether you like it or not, which is "When are two datetimes the same thing?" For example are these two date times the same?

```
>>> datetime.datetime.now(pytz.timezone('US/Arizona')).isoformat()
'2018-03-29T13:55:41.317599-07:00'
>>> datetime.datetime.now(pytz.timezone('US/Pacific')).isoformat()
'2018-03-29T13:55:50.738430-07:00'
```

Their `isoformat` output surely is (okay in this example they're off by a few hundred ms, but you get the picture. But those two timezones differ materially: Arizona doesn't observe daylight savings. (They of course represent the same point in time, but it's not clear that that in itself makes two datetimes "the same"; I would argue it doesn't.) I'm not totally sure how this behavior plays out, but I'm fairly certain there are going to be cases in individual client code where the difference may matter. (Imagine the trivial case of a function called `get_pytz_timezone_name` that returns `"US/Arizona"` for one and `"US/Pacific"` for the other!)

Not sure where exactly this leaves us. If you find some way to serialize the timezone name and make sure that gets included, I'm into it.

Cheers,
Danny

**Comment by benrudolph** [comment]
Yeah hmm, instead could perhaps use `strftime` with `%Z` which will put the string version of the timezone and blank for timezone naive datetimes

**Comment by millerdev** [comment]
Played around with this for a bit because I was confused by @dannyroberts example above. The two dates in that example are NOT the same—they're off by almost 10 seconds. I was confused by that and initially thought he may have been advocating for some kind of fuzzy matching that discards small time differences, but the same argument could be made for float values so that didn't make sense. Anyway, here's some code:
```py
>>> import datetime
>>> import pytz
>>> now = datetime.datetime.now(pytz.timezone('UTC'))
>>> now
datetime.datetime(2018, 3, 30, 11, 48, 15, 255346, tzinfo=<UTC>)
>>> az_now = now.astimezone(pytz.timezone('US/Arizona'))
>>> pc_now = now.astimezone(pytz.timezone('US/Pacific'))
>>> az_now
datetime.datetime(2018, 3, 30, 4, 48, 15, 255346, tzinfo=<DstTzInfo 'US/Arizona' MST-1 day, 17:00:00 STD>)
>>> pc_now
datetime.datetime(2018, 3, 30, 4, 48, 15, 255346, tzinfo=<DstTzInfo 'US/Pacific' PDT-1 day, 17:00:00 DST>)
>>> az_now == pc_now
True
>>> az_now.isoformat() == pc_now.isoformat()
True
>>> repr(az_now) == repr(pc_now)
False
```
One trivial way to make them differ would be to use `repr` before comparing if you need datetimes with different timezones to break the cache. However, I don't think that's a good idea. Since `az_now == pc_now` returns `True`, it seems reasonable to have quickcache consider these two dates as equal. This seems intuitive to me, especially given how it coerces bytes and unicode to mean the same thing even when they are not equal.

Alternately, maybe it would make sense to add a feature where custom serialization functions could be registered with quickcache so this behavior can be customized?

**Comment by benrudolph** [comment]
I tend to agree with @millerdev on this and that adding timezone into the equation makes it unnecessarily complex. RE danny's example I think @dannyroberts was using the `now` as a convenience function to show me how two datetimes can differ based on their timezone while being the same actual point in time even though they were slightly off because he just repeated the call twice

**Comment by millerdev** [comment]
Extending my example above a bit more
```py
>>> now == pc_now
True
>>> now.isoformat() == pc_now.isoformat()
False
```
Want to make sure that detail is not overlooked. Do we want differing timzone offsets (`isoformat` differences) to break the cache? I think it's a bit more intuitive to only break the cache when comparing the `datetime` instances returns False. This may be a bit more tricky to implement (although I think not much).

I think a more important question is whether to break the cache when comparing a offset-aware date with am offset-naive date. My gut response is a date with a timezone is a fundamentally different thing than one without a timezone, so it should break the cache. This may violate the date conventions in HQ.
```py
>>> not_now = now.replace(tzinfo=None)
>>> not_now == now
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by benrudolph** [comment]
Yes, that's a good point. Got to love datetimes. I wouldn't mind making the behavior be the same as datetime comparisons.

RE offset-aware vs. unaware, I think it should also break the cache. I think it would be weird otherwise

**Comment by dannyroberts** [comment]
+1 to following python's lead and making the behavior the same as datetime
comparisons. Since it's a legitimately reasonable question what it means
for two datetimes to be equal, let's go with the definition the standard
library has already picked for us. If someone wants to vary on the
timezone, they can always specify something like `<date arg>.tzinfo.zone`
in their `vary_on`.

**Comment by benrudolph** [comment]
https://github.com/dimagi/quickcache/pull/10
